### ISSUE TITLE
AttributeError: 'module' object has no attribute 'parse'

### ISSUE THREAD

**Issue by kostrovart** [omgovich/sublime-typograf#1]
Hello!
I extremely grateful for your plugin! It has made my work much easier! But I have a problem. Sometimes, not always, it doesn't work. And, in this case I need to reload Sublime.

My console output:

DPI scale: 1
startup, version: 3103 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/%USER%/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/%USER%/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/%USER%/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.481003
loading dictionary Packages/User/russian_english.dic
startup time: 1.018
first paint time: 1.02
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.profile_syntax_definition
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Python.syntax_test_python
reloading plugin User.Typograf
plugins loaded
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, *_args)
  File "C:\Users\%USER%\AppData\Roaming\Sublime Text 3\Packages\User\Typograf.py", line 11, in run
    params = urllib.parse.urlencode({ 'text': source, 'chr': 'UTF-8', 'xml': xml })
AttributeError: 'module' object has no attribute 'parse'
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, *_args)
  File "C:\Users\%USER%\AppData\Roaming\Sublime Text 3\Packages\User\Typograf.py", line 11, in run
    params = urllib.parse.urlencode({ 'text': source, 'chr': 'UTF-8', 'xml': xml })
AttributeError: 'module' object has no attribute 'parse'

**Comment by omgovich** [comment]
Hi, thx for your issue.
In your log, i see problem with Python "urllib" module.
Maybe in your Sublime was installed other version of this module. I thinks about it and try to fix it soon.

**Comment by kostrovart** [comment]
Thanks! In addition, I've used this plugin on different machines (Windows and Linux) and this problem  also has happened.

**Comment by agilesteel** [comment]
Hi, has this been resolved? I'm having exactly the same issue over here with a plugin I've written https://github.com/DevInsideYou/SpotifyWeb/issues/1
